### ISSUE TITLE
fout tijdens installatie

### ISSUE THREAD

**Issue by Ewout44** [JaccoR/hass-entso-e#160] opened 2024-06-28 08:50 UTC
wanneer ik integratie wil toevoegen komt HA met volgende fout.

Config-flow kon niet geladen worden: {"message":"Invalid handler specified"}

Is hier oplossing voor?

BVD

**Comment by marcovaneck** [comment] 2024-07-05 07:40
I had the same issue, strange enough I could fix it by restarting the complete Home Assistant instance in **debug** mode. After the install I reverted the logger back to **info** and it still works. 

these lines in configuration.yaml
```yaml
logger:
  default: debug
```

**Comment by Roeland54** [comment] 2024-08-31 11:39
v0.4.0 is released this version contains fixes that solve a lot of warnings and known issues. This issue is probably also solved.
Please update to the latest version.
Closing this issue for now. If you still have issue please feel free to open a new issue.

**Closed by Roeland54** 2024-08-31 11:39 UTC

**Comment by harkoprinssen** [comment] 2024-09-05 18:50
Issue still exists on latest version of HA and latest version (0.4.2) of the add-on

**Comment by Roeland54** [comment] 2024-09-05 20:16
duplicate of #56
