### ISSUE TITLE
"message":"Invalid handler specified

### ISSUE THREAD

**Issue by KHWW** [JaccoR/hass-entso-e#56] opened 2022-10-30 18:15 UTC
Hi, Maybe it's a typical amateur error..... But... I get the following message and it won't install the integration.

"message":"Invalid handler specified

![Foutmelding](https://user-images.githubusercontent.com/57412490/198894567-9c769c41-7437-4080-b3b8-c90578351d48.PNG)

**Comment by JaccoR** [comment] 2022-10-30 18:55
I can not reproduce this. Does this happen when you add the integration in your settings? Maybe try a hard refresh (ctrl+r).

**Comment by KHWW** [comment] 2022-10-30 19:25
Yes, when I add the integration in settings, I tried the intergration with HACS and also with manual install..  

I did the hard refresh, but is still not working...

**Comment by JaccoR** [comment] 2022-10-30 19:54
What name are you using, are you using any special characters?

**Comment by KHWW** [comment] 2022-10-30 20:11
The name of?  Then I can check.

**Comment by JaccoR** [comment] 2022-10-31 15:14
I meant the name you give the integration, but since you can not set it up you never gave it a name of course. 
This seems to have to do with the entsoe library i'm using to call for entso-e data. I can not do anything about this atm. 

You could try a different python version, if that is not too much of a hassle. I am running python 3.9.

**Comment by MrTheoW** [comment] 2022-11-01 12:36
I currently running the latest version of HAOS and am seeing the same error come by.
Is there any chance this custom integration will be updated so it will work with Python 3.10?
I think there will be a lot of people getting this error if they stick to the updates of Home Assistant...

**Comment by MrTheoW** [comment] 2022-11-01 12:41
Funny thing is that according to the file location (/usr/local/lib/python3.10/site-packages/bs4/builder/init.py) you could assume I would be running python 3.10 but once I navigate to that location only python3.9 exists.

**Comment by sfstar** [comment] 2022-11-02 16:49
Weird that it is not working for you.
By latest version do you refer to the 2022.10.5 release?
(This is the version I am running and the integration is working at my end).
Could you perhaps try to remove the integration files and force redownload the latest release from hacs again?

**Comment by MrTheoW** [comment] 2022-11-08 03:31
Bit late to react but didn't see the notification.

HAOS version: 2022.11.1

Removed the component from HACS and installed the latest version from HACS (0.1.3).

Still gives the same error.

![image](https://user-images.githubusercontent.com/12528577/200468581-2e5d492a-daa5-4774-8a93-12d23373a119.jpeg)

![image](https://user-images.githubusercontent.com/12528577/200468600-7f1b196f-9851-464d-bea5-72e8a613e39a.jpeg)

**Comment by MrTheoW** [comment] 2022-11-08 10:14
If I can help you with anything please tell me.

**Comment by JaccoR** [comment] 2022-11-26 13:48
Did you already find a solution for this?

**Comment by Mipilo** [comment] 2022-12-20 09:16
Hi there,

I have the same problem as MrTheoW.
Versions:
HA: 2022.12.7
HACS: 1.29.0
ENTSO-E: 0.3.0
Python: 3.10.7

If there is a solution I would like to hear it.

**Comment by MrTheoW** [comment] 2022-12-20 13:06
> Did you already find a solution for this?

No, Unfortunately I do not know how to change the Python version in HA OS so it remains on version 3.9.
And to be honest, It actually scares me a bit to do a manual update just before the holidays. If anything goes wrong and I wont be able to fix it in time I think I might sleep on the couch during the year change. 😅

**Comment by TFhdKi95ae8L** [comment] 2022-12-26 21:17
Same "Config flow could not be loaded: {"message":"Invalid handler specified"}" error here.
Installed via Hacs, tried adding the integration and the error mentioned above appears.
Any advice on what to try?

**Comment by sga-noud** [comment] 2023-09-10 21:22
Running HA Core 2023.7.3 and getting this same error after downloading 0.3.0 from HACS and trying to add the integration. Still no Python 3.10 support?

**Comment by Roeland54** [comment] 2024-09-13 12:46
Probably fixed in [v0.5.0-beta2](https://github.com/JaccoR/hass-entso-e/releases/tag/v0.5.0-beta2). 
Please test and provide feedback.

**Comment by Roeland54** [comment] 2024-09-19 13:16
v0.5.0 is released. The discussed issues should be solved. Please feel free to open a new issue if you feel this is needed.

**Closed by Roeland54** 2024-09-19 13:16 UTC
