### ISSUE TITLE
Doesn't work annymore

### ISSUE THREAD

**Issue by PjotrBaas** [JaccoR/hass-entso-e#174] opened 2024-09-10 07:28 UTC
Since the HA updates in august i have to re-install everything. I realy hope this problem can be fixed.
Thank you very much for all your effort in creating this automation, i've used it a long time and it was a pleasure to use it.

Update: i run HA OS (on Raspberrypi 4) 
core 2024.9.1
Supervisor 2024.08.0
OS 13.1
Frontend 20240906.0

I can intall the integration again, but after updating to a new version of HA Core or Supervisor it doesn't work anymore (waiting a view days doesn't help). Then i have to delete the integration and delete Entso-e from HACS => deleting the integration alone and re-installing doesn't work. Then download Entso-e again, restart HA, install the integration. 
To me it seems it has something to do with apps getting data from 3rd party websites: i had another simular app that acted the same after updating HA (i stopped using it for this reason).

**Comment by Roeland54** [comment] 2024-09-10 13:48
For us to be able to help you and determine the cause of your issue you will need to provide more information on where it goes wrong. Things like HA installation type, error messages, logs, screenshots?

> I assume something has changed in HA, making it less friendly for HACS. 

This statement is definitely not correct HACS became part of the "open home foundation" it's support in HA should even improve.

**Comment by Roeland54** [comment] 2024-09-10 19:53
I am going to need some logs to be able to diagnose this. 

1. Enable debug logging for the integration:

![image](https://github.com/user-attachments/assets/397ed710-f26b-42d8-ae74-6bdb49817782)
2. Reload the integration:
![image](https://github.com/user-attachments/assets/a1a28f89-d875-4242-8635-083279348726)
3. Disable debug logging. You will get a logfile when disabling.
4. Search for "entsoe" in the logfile an copy relevant parts here.


> Since the HA updates in august i have to re-install everything. 
> 
> To me it seems it has something to do with apps getting data from 3rd party websites: i had another simular app that acted the same after updating HA (i stopped using it for this reason).

These things al sound like you have a setup/environment/network issue unrelated to this integration.

**Comment by PjotrBaas** [comment] 2024-09-11 15:23
Oké, thanks for looking in to my problem. Since i'm the only one having this problem, the cause of it must be on my side.

**Comment by Roeland54** [comment] 2024-09-19 13:11
I am going to close this issue. As there is not enough information to proceed.

**Closed by Roeland54** 2024-09-19 13:11 UTC
