### ISSUE TITLE
missing prices for hours with same price as the hour before

### ISSUE THREAD

**Issue by Aelbaert** [JaccoR/hass-entso-e#192] opened 2024-10-06 12:57 UTC
In using the prices to determine the hours my car can be loaded for the lowest price, on several occasions the 'Current electricity market price'  and prices today at certain times are not available (see: ![image](https://github.com/user-attachments/assets/61388610-9d7d-49fe-ba5b-0e32dca387c3)).
I don't know how to work around this by scripting (sorry, I'm new at this), so could anybody point me at a solution for this?
I'm looking for a script that can handle missing data, but still give the n-lowest price of the day (as being the trigger to flip the charging switch).

**Comment by Pluimvee** [comment] 2024-10-06 13:11
Resolved in the pull-request

**Comment by Aelbaert** [comment] 2024-10-06 13:21
Thank you. I'm still looking for a way to work around missing attributes, but for now this will probably solve my problem as well. :-)

**Comment by Roeland54** [comment] 2024-10-06 13:53
duplicate of #190

**Closed by Roeland54** 2024-10-06 13:53 UTC
